### ISSUE TITLE
更新了最新版本，ActorShape makeShapeNode方法提示冲突；

### ISSUE THREAD

**Issue by lcyluo** [phoenixsky/fun_android_flutter#21]
Compiler message:                                                       
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flare_flutter-1.5.5/lib/flare.dart:585:14: Error: The method 'FlutterActor.makeShapeNode' has fewer positional arguments than those of overridden method 'Actor.makeShapeNode'.
  ActorShape makeShapeNode() {                                          
             ^                                                          
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flare_dart-1.4.7/lib/actor.dart:68:14: Context: This is the overridden method ('makeShapeNode').
  ActorShape makeShapeNode(ActorShape source) {                         
             ^                                                          
Compiler failed

以上是编译日志，我再运行flutter run编译时，遇到了这个问题，但是我这边不知道如何解决，恳请大大帮忙看一下。

**Comment by phoenixsky** [comment]
flutter sdk版本是什么?

**Comment by lcyluo** [comment]
Flutter 1.9.1+hotfix.2

**Comment by phoenixsky** [comment]
看下你的pubspec.lock.
我这里的flare_dart是1.4.5,你那里是1.4.7? 

你试试把两个库的版本都更新为最新的

```
  flare_dart:
    dependency: transitive
    description:
      name: flare_dart
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.4.5"
  flare_flutter:
    dependency: "direct main"
    description:
      name: flare_flutter
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.5.5"
```
